#配置端口
server:
  port: 9100

spring:

  #mysql服务
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://199.168.0.249:3307/updata_data_source?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: huijianzhu
    ##这样就不会使用Springboot默认的连接池Hikari。
    type: com.alibaba.druid.pool.DruidDataSource

  #Redis服务
  redis:
    #Redis数据库索引（默认为0）
    database: 10
    #Redis连接地址
    host: www.king2.cn
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: liuzijiang1314
    #连接超时时间（毫秒）
    timeout: 1000